# Generated by Django 6.0.4 on 2026-05-16 17:55

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMethod',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'طريقة إضافة',
                'verbose_name_plural': 'طرق الإضافة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_url', models.URLField(max_length=1000)),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('FILE', 'File')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Field Name')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('boolean', 'Boolean')], max_length=20, verbose_name='Field Type')),
                ('is_required', models.BooleanField(default=False, verbose_name='Is Required?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Custom Field Definition',
                'verbose_name_plural': 'Custom Field Definitions',
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField(verbose_name='Value')),
                ('object_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Custom Field Value',
                'verbose_name_plural': 'Custom Field Values',
            },
        ),
        migrations.CreateModel(
            name='DailyTaskReport',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مقدم'), ('under_review', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='draft', max_length=20, verbose_name='حالة التقرير')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('report_date', models.DateField(verbose_name='تاريخ التقرير')),
                ('company_workers', models.PositiveIntegerField(default=0, verbose_name='عمال الشركة')),
                ('contractor_workers', models.PositiveIntegerField(default=0, verbose_name='عمال المقاول')),
                ('actual_productivity', models.FloatField(blank=True, null=True, verbose_name='الانتاجية الفعلية')),
                ('work_hours', models.FloatField(verbose_name='ساعات العمل')),
                ('overtime_hours', models.FloatField(blank=True, null=True, verbose_name='ساعات الإضافي')),
                ('overtime_productivity', models.FloatField(blank=True, null=True, verbose_name='انتاجية الإضافي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('override_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التعديل الاستثنائي')),
                ('override_reason', models.TextField(blank=True, null=True, verbose_name='سبب التعديل')),
                ('was_overridden', models.BooleanField(default=False, verbose_name='تم تعديله استثنائياً')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التقديم')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرفض')),
            ],
            options={
                'verbose_name': 'تقرير مهام يومي',
                'verbose_name_plural': 'تقارير المهام اليومية',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FertilizationReport',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField(verbose_name='تاريخ')),
                ('variety', models.CharField(max_length=30, verbose_name='الصنف')),
                ('material_name', models.CharField(max_length=100, verbose_name='المادة الفعالة')),
                ('active_percentage', models.FloatField(blank=True, null=True, verbose_name='النسبة %')),
                ('rate_per_feddan', models.FloatField(blank=True, null=True, verbose_name='معدل الفدان')),
                ('transfer_number', models.IntegerField(blank=True, null=True, verbose_name='رقم التحويلة')),
                ('valves', models.CharField(blank=True, max_length=50, verbose_name='المحابس')),
                ('area_feddan', models.FloatField(blank=True, null=True, verbose_name='المساحة (فدان)')),
                ('tree_count', models.IntegerField(blank=True, null=True, verbose_name='عدد الأشجار')),
                ('total_quantity', models.FloatField(blank=True, null=True, verbose_name='إجمالي الكمية')),
                ('operator', models.CharField(blank=True, max_length=100, verbose_name='القائم بالعمل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'تقرير تسميد',
                'verbose_name_plural': 'تقارير التسميد',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationReport',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField(verbose_name='تاريخ')),
                ('sector_number', models.IntegerField(verbose_name='رقم القطاع')),
                ('transfer_number', models.IntegerField(verbose_name='رقم التحويلة')),
                ('area_feddan', models.FloatField(blank=True, null=True, verbose_name='المساحة (فدان)')),
                ('tree_count', models.IntegerField(blank=True, null=True, verbose_name='عدد النخيل')),
                ('well_flow_m3', models.FloatField(blank=True, null=True, verbose_name='تصرف البئر م³/ساعة')),
                ('water_per_tree', models.FloatField(blank=True, null=True, verbose_name='كمية المياه للنخلة')),
                ('irrigation_hours', models.FloatField(blank=True, null=True, verbose_name='ساعات الري')),
                ('irrigation_cycles', models.IntegerField(blank=True, null=True, verbose_name='مرات الري')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'تقرير ري',
                'verbose_name_plural': 'تقارير الري',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='LaborCategory',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Labor Category',
                'verbose_name_plural': 'Labor Categories',
            },
        ),
        migrations.CreateModel(
            name='LaborEntry',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker_name', models.CharField(max_length=120)),
                ('worker_type', models.CharField(choices=[('COMPANY', 'Company'), ('CONTRACTOR', 'Contractor')], max_length=20)),
                ('worker_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('profile_type', models.CharField(default='generic', max_length=50)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('pollination', 'تلقيح ومشاتل'), ('planting', 'زراعة وفسائل'), ('maintenance', 'صيانة ونظافة'), ('fertilization', 'تسميد'), ('protection', 'مكافحة'), ('monitoring', 'متابعة وإشراف'), ('transport', 'نقل وتحميل'), ('other', 'أخرى')], default='other', max_length=50)),
                ('json_schema', models.JSONField(blank=True, help_text='JSON Schema (Draft-7) rules for validating profile_data', null=True)),
                ('ui_schema', models.JSONField(blank=True, help_text='UI definitions for rendering forms and timeline fields', null=True)),
                ('schema_version', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'عملية فنية',
                'verbose_name_plural': 'العمليات الفنية',
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(blank=True, choices=[('DAILY_TASK', 'Daily Task Report'), ('HARVEST', 'Harvest Report'), ('SORTING', 'Sorting Report')], db_index=True, max_length=50, null=True)),
                ('source_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('chain_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='كود السلسلة')),
                ('company_workers', models.PositiveIntegerField(default=0, verbose_name='عمال الشركة')),
                ('contractor_workers', models.PositiveIntegerField(default=0, verbose_name='عمال المقاول')),
                ('actual_productivity', models.FloatField(blank=True, null=True, verbose_name='الانتاجية الفعلية')),
                ('work_hours', models.FloatField(default=0.0, verbose_name='ساعات العمل')),
                ('overtime_hours', models.FloatField(blank=True, null=True, verbose_name='ساعات الإضافي')),
                ('overtime_productivity', models.FloatField(blank=True, null=True, verbose_name='انتاجية الإضافي')),
                ('sequence', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('profile_type', models.CharField(default='generic', max_length=50)),
                ('profile_version', models.IntegerField(default=1)),
                ('profile_data', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('bulk_operation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('COMPLETED', 'تم التنفيذ'), ('FAILED', 'فشل التنفيذ'), ('SKIPPED', 'تم التخطي')], default='COMPLETED', max_length=20)),
            ],
            options={
                'verbose_name': 'سجل عملية',
                'verbose_name_plural': 'سجلات العمليات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackagingType',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Packaging Type',
                'verbose_name_plural': 'Packaging Types',
            },
        ),
        migrations.CreateModel(
            name='ProductivityClassification',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Productivity Classification',
                'verbose_name_plural': 'Productivity Classifications',
            },
        ),
        migrations.CreateModel(
            name='QualityGrade',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Quality Grade',
                'verbose_name_plural': 'Quality Grades',
            },
        ),
        migrations.CreateModel(
            name='ReportDropdownOption',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('variety', 'Variety'), ('unit', 'Unit'), ('contractor', 'Contractor'), ('enclosure', 'Enclosure'), ('work_location', 'Work Location')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'مفتوح'), ('CLOSED', 'مغلق'), ('ARCHIVED', 'مؤرشف')], default='OPEN', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'موسم',
                'verbose_name_plural': 'المواسم',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SortingCategory',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sorting Category',
                'verbose_name_plural': 'Sorting Categories',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Variety',
                'verbose_name_plural': 'Varieties',
                'ordering': ['name'],
            },
        ),
    ]
