# Generated by Django 6.0.4 on 2026-05-16 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('farm', '0002_initial'),
        ('reports', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmethod',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='customfielddefinition',
            name='applies_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Applies to Model'),
        ),
        migrations.AddField(
            model_name='customfielddefinition',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='customfielddefinition',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='customfieldvalue',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='customfieldvalue',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='customfieldvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='reports.customfielddefinition'),
        ),
        migrations.AddField(
            model_name='dailytaskreport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='dailytaskreport',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_task_reports', to='reports.contractor', verbose_name='كود المقاول'),
        ),
        migrations.AddField(
            model_name='dailytaskreport',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_reports', to=settings.AUTH_USER_MODEL, verbose_name='تم الحذف بواسطة'),
        ),
        migrations.AddField(
            model_name='dailytaskreport',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to=settings.AUTH_USER_MODEL, verbose_name='المهندس'),
        ),
        migrations.AddField(
            model_name='dailytaskreport',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_task_reports', to='farm.locationnode'),
        ),
        migrations.AddField(
            model_name='dailytaskreport',
            name='override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_reports', to=settings.AUTH_USER_MODEL, verbose_name='المعدل الاستثنائي'),
        ),
        migrations.AddField(
            model_name='dailytaskreport',
            name='work_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_task_work_reports', to='farm.locationnode', verbose_name='مكان العمل'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.dailytaskreport'),
        ),
        migrations.AddField(
            model_name='fertilizationreport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='irrigationreport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='laborcategory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='laborentry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='laborentry',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='labor_entries', to='reports.contractor'),
        ),
        migrations.AddField(
            model_name='laborentry',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_entries', to='reports.dailytaskreport'),
        ),
        migrations.AddField(
            model_name='operation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='dailytaskreport',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.operation', verbose_name='العملية الفنية'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_logs', to='reports.contractor', verbose_name='كود المقاول'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_operation_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_logs', to='farm.locationnode'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.operation', verbose_name='العملية الفنية'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='parent_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_logs', to='reports.operationlog', verbose_name='العملية الأب'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='reports.dailytaskreport', verbose_name='التقرير الحاوي'),
        ),
        migrations.AddField(
            model_name='laborentry',
            name='operation_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_entries', to='reports.operationlog'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='operation_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.operationlog'),
        ),
        migrations.AddField(
            model_name='packagingtype',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='productivityclassification',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='qualitygrade',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='reportdropdownoption',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='season',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_logs', to='reports.season'),
        ),
        migrations.AddField(
            model_name='sortingcategory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='unit',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='users.company'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_logs', to='reports.unit', verbose_name='الوحدة'),
        ),
        migrations.AddField(
            model_name='dailytaskreport',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_task_reports', to='reports.unit', verbose_name='الوحدة'),
        ),
        migrations.AddField(
            model_name='variety',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='users.company'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_logs', to='reports.variety', verbose_name='الصنف'),
        ),
        migrations.AddField(
            model_name='dailytaskreport',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_task_reports', to='reports.variety', verbose_name='الصنف'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationmethod',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='contractor',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='customfieldvalue',
            unique_together={('field', 'content_type', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='laborcategory',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='operation',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='laborentry',
            index=models.Index(fields=['company', 'report'], name='reports_lab_company_404f0b_idx'),
        ),
        migrations.AddIndex(
            model_name='laborentry',
            index=models.Index(fields=['report', 'worker_type'], name='reports_lab_report__86f536_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['company', 'uploaded_at'], name='reports_att_company_510d0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='packagingtype',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='productivityclassification',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='qualitygrade',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='reportdropdownoption',
            unique_together={('company', 'name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='sortingcategory',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='variety',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['company', 'operation', 'created_at'], name='reports_ope_company_b15b18_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['company', 'location', 'created_at'], name='reports_ope_company_046f3b_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['source_type', 'source_id'], name='reports_ope_source__46f3a3_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytaskreport',
            index=models.Index(fields=['company', 'report_date'], name='reports_dai_company_711999_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytaskreport',
            index=models.Index(fields=['company', 'operation', 'report_date'], name='reports_dai_company_765387_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytaskreport',
            index=models.Index(fields=['report_date'], name='reports_dai_report__2343ce_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytaskreport',
            index=models.Index(fields=['engineer', 'report_date'], name='reports_dai_enginee_b3d8d7_idx'),
        ),
    ]
