# Generated by Django 6.0.4 on 2026-04-26 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FertilizationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="تاريخ")),
                ("variety", models.CharField(max_length=30, verbose_name="الصنف")),
                (
                    "material_name",
                    models.CharField(max_length=100, verbose_name="المادة الفعالة"),
                ),
                (
                    "active_percentage",
                    models.FloatField(blank=True, null=True, verbose_name="النسبة %"),
                ),
                (
                    "rate_per_feddan",
                    models.FloatField(
                        blank=True, null=True, verbose_name="معدل الفدان"
                    ),
                ),
                (
                    "transfer_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="رقم التحويلة"
                    ),
                ),
                (
                    "valves",
                    models.CharField(blank=True, max_length=50, verbose_name="المحابس"),
                ),
                (
                    "area_feddan",
                    models.FloatField(
                        blank=True, null=True, verbose_name="المساحة (فدان)"
                    ),
                ),
                (
                    "tree_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="عدد الأشجار"
                    ),
                ),
                (
                    "total_quantity",
                    models.FloatField(
                        blank=True, null=True, verbose_name="إجمالي الكمية"
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="القائم بالعمل"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
            ],
            options={
                "verbose_name": "تقرير تسميد",
                "verbose_name_plural": "تقارير التسميد",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="IrrigationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="تاريخ")),
                ("sector_number", models.IntegerField(verbose_name="رقم القطاع")),
                ("transfer_number", models.IntegerField(verbose_name="رقم التحويلة")),
                (
                    "area_feddan",
                    models.FloatField(
                        blank=True, null=True, verbose_name="المساحة (فدان)"
                    ),
                ),
                (
                    "tree_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="عدد النخيل"
                    ),
                ),
                (
                    "well_flow_m3",
                    models.FloatField(
                        blank=True, null=True, verbose_name="تصرف البئر م³/ساعة"
                    ),
                ),
                (
                    "water_per_tree",
                    models.FloatField(
                        blank=True, null=True, verbose_name="كمية المياه للنخلة"
                    ),
                ),
                (
                    "irrigation_hours",
                    models.FloatField(blank=True, null=True, verbose_name="ساعات الري"),
                ),
                (
                    "irrigation_cycles",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="مرات الري"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
            ],
            options={
                "verbose_name": "تقرير ري",
                "verbose_name_plural": "تقارير الري",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("harvest", "حصاد"),
                            ("planting", "زراعة"),
                            ("maintenance", "صيانة"),
                            ("pest_control", "مكافحة"),
                            ("transport", "نقل وتحميل"),
                            ("other", "أخرى"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "عملية فنية",
                "verbose_name_plural": "العمليات الفنية",
            },
        ),
        migrations.CreateModel(
            name="DailyTaskReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="تاريخ التقرير")),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("greenhouse", "الصوب"),
                            ("new_farms", "الزراعات الجديدة"),
                            ("all", "كل المزرعة"),
                        ],
                        max_length=20,
                        verbose_name="القطاع",
                    ),
                ),
                (
                    "variety",
                    models.CharField(
                        choices=[
                            ("medjool", "مجدول"),
                            ("saidi", "صعيدي"),
                            ("lemon", "ليمون"),
                            ("medjool_lemon", "مجدول + ليمون"),
                            ("farihi", "فريحي"),
                            ("greenhouse", "الصوب"),
                            ("all", "كل الأصناف"),
                            ("other", "أخرى"),
                        ],
                        max_length=30,
                        verbose_name="الصنف",
                    ),
                ),
                (
                    "enclosure",
                    models.CharField(blank=True, max_length=100, verbose_name="الحوشة"),
                ),
                (
                    "work_location",
                    models.CharField(max_length=100, verbose_name="مكان العمل"),
                ),
                (
                    "company_workers",
                    models.PositiveIntegerField(default=0, verbose_name="عمال الشركة"),
                ),
                (
                    "contractor_workers",
                    models.PositiveIntegerField(default=0, verbose_name="عمال المقاول"),
                ),
                (
                    "contractor_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="كود المقاول"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("seedling", "فسيلة"),
                            ("palm", "نخلة"),
                            ("pit", "جورة"),
                            ("enclosure", "حوشة"),
                            ("preparation", "تحضيرة"),
                            ("cone", "كوز"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="الوحدة",
                    ),
                ),
                (
                    "actual_productivity",
                    models.FloatField(
                        blank=True, null=True, verbose_name="الانتاجية الفعلية"
                    ),
                ),
                ("work_hours", models.FloatField(verbose_name="ساعات العمل")),
                (
                    "overtime_hours",
                    models.FloatField(
                        blank=True, null=True, verbose_name="ساعات الإضافي"
                    ),
                ),
                (
                    "overtime_productivity",
                    models.FloatField(
                        blank=True, null=True, verbose_name="انتاجية الإضافي"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظة")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "engineer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المهندس",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.operation",
                        verbose_name="العملية الفنية",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقرير مهام يومي",
                "verbose_name_plural": "تقارير المهام اليومية",
                "ordering": ["-report_date", "engineer"],
            },
        ),
        migrations.DeleteModel(
            name="DailyReport",
        ),
        migrations.AddIndex(
            model_name="dailytaskreport",
            index=models.Index(
                fields=["report_date"], name="reports_dai_report__2343ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailytaskreport",
            index=models.Index(
                fields=["engineer", "report_date"],
                name="reports_dai_enginee_b3d8d7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dailytaskreport",
            index=models.Index(
                fields=["sector", "report_date"], name="reports_dai_sector_6c9d27_idx"
            ),
        ),
    ]
