# Generated by Django 6.0.4 on 2026-05-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldvalue',
            name='object_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
