# Generated by Django 6.0.4 on 2026-05-17 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employee_monthly_salary_employee_standard_work_hours_and_more'),
        ('reports', '0003_alter_customfieldvalue_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborentry',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='laborentry',
            name='deduction_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='laborentry',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_entries', to='hr.worker'),
        ),
    ]
