# Generated by Django 6.0.4 on 2026-05-20 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_initial'),
        ('reports', '0004_laborentry_deduction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborentry',
            name='harvest_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_entries', to='production.harvestreport'),
        ),
        migrations.AlterField(
            model_name='laborentry',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_entries', to='reports.dailytaskreport'),
        ),
    ]
