# Generated by Django 6.0.4 on 2026-05-20 22:36

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_laborentry_harvest_report_alter_laborentry_report'),
        ('users', '0005_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationmethod',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='applicationmethod',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='laborentry',
            name='deduction_amount',
        ),
        migrations.RemoveField(
            model_name='laborentry',
            name='deduction_hours',
        ),
        migrations.RemoveField(
            model_name='laborentry',
            name='worker',
        ),
        migrations.AlterField(
            model_name='applicationmethod',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customfielddefinition',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_definitions', to='users.company'),
        ),
        migrations.AlterField(
            model_name='customfieldvalue',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='fertilizationreport',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fertilization_reports', to='users.company'),
        ),
        migrations.AlterField(
            model_name='irrigationreport',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_reports', to='users.company'),
        ),
        migrations.AlterField(
            model_name='reportdropdownoption',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_options', to='users.company'),
        ),
        migrations.CreateModel(
            name='GalleryMedia',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_url', models.URLField(max_length=1000)),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('FILE', 'File')], default='IMAGE', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
