# Generated by Django 6.0.4 on 2026-05-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_applicationmethod_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytaskreport',
            name='contractors',
            field=models.ManyToManyField(blank=True, related_name='daily_task_reports_m2m', to='reports.contractor', verbose_name='المقاولون'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='contractors',
            field=models.ManyToManyField(blank=True, related_name='operation_logs_m2m', to='reports.contractor', verbose_name='المقاولون'),
        ),
    ]
