# Generated by Django 6.0.4 on 2026-04-26 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_crop_stage_enclosure'),
        ('reports', '0006_remove_dailytaskreport_reports_dai_sector__5403c8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytaskreport',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='farm.crop', verbose_name='المحصول'),
        ),
    ]
