# Generated by Django 6.0.4 on 2026-05-24 21:42

import django.db.models.deletion
import django.utils.timezone
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('farm', '0002_initial'),
        ('reports', '0007_dailytaskreport_contractors_operationlog_contractors'),
        ('users', '0007_user_avatar_url'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='irrigationreport',
            options={'ordering': ['-date'], 'verbose_name': 'تقرير ري', 'verbose_name_plural': 'تقارير الري'},
        ),
        migrations.RemoveField(
            model_name='irrigationreport',
            name='area_feddan',
        ),
        migrations.RemoveField(
            model_name='irrigationreport',
            name='irrigation_cycles',
        ),
        migrations.RemoveField(
            model_name='irrigationreport',
            name='irrigation_hours',
        ),
        migrations.RemoveField(
            model_name='irrigationreport',
            name='report_date',
        ),
        migrations.RemoveField(
            model_name='irrigationreport',
            name='sector_number',
        ),
        migrations.RemoveField(
            model_name='irrigationreport',
            name='transfer_number',
        ),
        migrations.RemoveField(
            model_name='irrigationreport',
            name='tree_count',
        ),
        migrations.RemoveField(
            model_name='irrigationreport',
            name='water_per_tree',
        ),
        migrations.RemoveField(
            model_name='irrigationreport',
            name='well_flow_m3',
        ),
        migrations.AddField(
            model_name='irrigationreport',
            name='attachments',
            field=models.JSONField(blank=True, default=list, verbose_name='المرفقات'),
        ),
        migrations.AddField(
            model_name='irrigationreport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='irrigationreport',
            name='engineer',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000001', on_delete=django.db.models.deletion.PROTECT, related_name='irrigation_reports_v2', to=settings.AUTH_USER_MODEL, verbose_name='المهندس المسؤول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='irrigationreport',
            name='is_fertilized',
            field=models.BooleanField(default=False, verbose_name='مع تسميد'),
        ),
        migrations.AddField(
            model_name='irrigationreport',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='إجمالي الساعات'),
        ),
        migrations.AddField(
            model_name='irrigationreport',
            name='total_shifts',
            field=models.IntegerField(default=0, verbose_name='إجمالي التحويلات'),
        ),
        migrations.AlterField(
            model_name='irrigationreport',
            name='company',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000001', on_delete=django.db.models.deletion.CASCADE, to='users.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='irrigationreport',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.CreateModel(
            name='IrrigationDetail',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shifts_count', models.IntegerField(verbose_name='عدد التحويلات')),
                ('hours_per_shift', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='عدد الساعات للتحويلة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.locationnode', verbose_name='المرحلة')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='reports.irrigationreport')),
            ],
            options={
                'verbose_name': 'تفاصيل الري',
                'verbose_name_plural': 'تفاصيل الري',
            },
        ),
        migrations.CreateModel(
            name='AppliedFertilizer',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_material_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم السماد الخارجي')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية')),
                ('unit', models.CharField(default='كجم', max_length=50, verbose_name='الوحدة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('fertilizer_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.item', verbose_name='السماد')),
                ('irrigation_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizers', to='reports.irrigationdetail')),
            ],
            options={
                'verbose_name': 'السماد المضاف',
                'verbose_name_plural': 'الأسمدة المضافة',
            },
        ),
        migrations.CreateModel(
            name='OperationalLocationAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('allocated_workers_company', models.IntegerField(default=0, verbose_name='عمال شركة')),
                ('allocated_workers_contractor_a', models.IntegerField(default=0, verbose_name='عمال مقاول أ')),
                ('allocated_workers_contractor_b', models.IntegerField(default=0, verbose_name='عمال مقاول ب')),
                ('productivity_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الإنتاجية للموقع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الموقع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('enclosure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.locationnode', verbose_name='الحوشة')),
            ],
            options={
                'verbose_name': 'توزيع العمليات على المواقع',
                'verbose_name_plural': 'توزيع العمليات على المواقع',
                'db_table': 'operational_location_allocations',
            },
        ),
        migrations.CreateModel(
            name='PestControlReport',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('custom_pesticide_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المبيد الخارجي')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية المستخدمة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='المرفقات')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='المهندس المسؤول')),
                ('pesticide_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.item', verbose_name='المبيد')),
            ],
            options={
                'verbose_name': 'تقرير مكافحة',
                'verbose_name_plural': 'تقارير المكافحة',
                'ordering': ['-date'],
            },
        ),
    ]
