# Generated by Django 6.0.4 on 2026-05-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_irrigationreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlog',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='source_type',
            field=models.CharField(blank=True, choices=[('DAILY_TASK', 'Daily Task Report'), ('HARVEST', 'Harvest Report'), ('SORTING', 'Sorting Report'), ('IRRIGATION', 'Irrigation Report'), ('PEST_CONTROL', 'Pest Control Report')], db_index=True, max_length=50, null=True),
        ),
    ]
