# Generated by Django 6.0.4 on 2026-05-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_operationlog_source_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationreport',
            name='company_workers',
            field=models.PositiveIntegerField(default=0, verbose_name='عمال الشركة'),
        ),
        migrations.AddField(
            model_name='irrigationreport',
            name='contractor_workers_a',
            field=models.PositiveIntegerField(default=0, verbose_name='عمال مقاول أ'),
        ),
        migrations.AddField(
            model_name='irrigationreport',
            name='contractor_workers_b',
            field=models.PositiveIntegerField(default=0, verbose_name='عمال مقاول ب'),
        ),
    ]
