# Generated by Django 6.0.4 on 2026-04-27 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0009_phase2_production_upgrade"),
        ("users", "0005_company_user_company"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="attachment",
            new_name="reports_att_company_510d0d_idx",
            old_name="reports_att_company_3d504f_idx",
        ),
        migrations.RenameIndex(
            model_name="dailytaskreport",
            new_name="reports_dai_company_711999_idx",
            old_name="reports_dai_company_d66d6d_idx",
        ),
        migrations.RenameIndex(
            model_name="dailytaskreport",
            new_name="reports_dai_company_765387_idx",
            old_name="reports_dai_company_4885f8_idx",
        ),
        migrations.RenameIndex(
            model_name="laborentry",
            new_name="reports_lab_company_404f0b_idx",
            old_name="reports_lab_company_af9c3c_idx",
        ),
        migrations.RenameIndex(
            model_name="laborentry",
            new_name="reports_lab_report__86f536_idx",
            old_name="reports_lab_report__4f6a8f_idx",
        ),
        migrations.AlterField(
            model_name="contractor",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.company"
            ),
        ),
        migrations.AlterField(
            model_name="customfielddefinition",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_field_definitions",
                to="users.company",
            ),
        ),
        migrations.AlterField(
            model_name="dailytaskreport",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.company"
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="category",
            field=models.CharField(
                choices=[
                    ("pollination", "تلقيح ومشاتل"),
                    ("planting", "زراعة وفسائل"),
                    ("maintenance", "صيانة ونظافة"),
                    ("fertilization", "تسميد"),
                    ("protection", "مكافحة"),
                    ("monitoring", "متابعة وإشراف"),
                    ("transport", "نقل وتحميل"),
                    ("other", "أخرى"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.company"
            ),
        ),
        migrations.AlterField(
            model_name="reportdropdownoption",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_options",
                to="users.company",
            ),
        ),
    ]
