# Generated by Django 6.0.4 on 2026-05-25 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_irrigationreport_company_workers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationreport',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irrigation_reports_v2_linked', to='reports.contractor', verbose_name='المقاول'),
        ),
        migrations.AddField(
            model_name='irrigationreport',
            name='contractor_workers',
            field=models.PositiveIntegerField(default=0, verbose_name='عمال المقاول'),
        ),
    ]
