# Generated by Django 6.0.4 on 2026-05-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_irrigationreport_contractor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='commercial_registry',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='السجل التجاري'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='tax_card',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='البطاقة الضريبية'),
        ),
    ]
