# Generated by GitHub Copilot on 2026-04-27

import django.db.models.deletion
from django.db import migrations, models


def migrate_report_dropdown_options(apps, schema_editor):
    Variety = apps.get_model('reports', 'Variety')
    Unit = apps.get_model('reports', 'Unit')
    Contractor = apps.get_model('reports', 'Contractor')
    ReportDropdownOption = apps.get_model('reports', 'ReportDropdownOption')
    DailyTaskReport = apps.get_model('reports', 'DailyTaskReport')

    variety_map = {}
    unit_map = {}
    contractor_map = {}

    for option in ReportDropdownOption.objects.filter(category='variety'):
        variety_obj, _ = Variety.objects.get_or_create(company=option.company, name=option.name)
        variety_map[option.pk] = variety_obj.pk

    for option in ReportDropdownOption.objects.filter(category='unit'):
        unit_obj, _ = Unit.objects.get_or_create(company=option.company, name=option.name)
        unit_map[option.pk] = unit_obj.pk

    for option in ReportDropdownOption.objects.filter(category='contractor'):
        contractor_obj, _ = Contractor.objects.get_or_create(
            company=option.company,
            name=option.name,
            defaults={'rate_per_hour': 0, 'is_active': True},
        )
        contractor_map[option.pk] = contractor_obj.pk

    for report in DailyTaskReport.objects.all():
        updated = False
        if report.variety_id:
            if report.variety_id not in variety_map:
                option = ReportDropdownOption.objects.filter(pk=report.variety_id).first()
                if option:
                    variety_obj, _ = Variety.objects.get_or_create(company=option.company, name=option.name)
                    variety_map[option.pk] = variety_obj.pk
            report.variety_new_id = variety_map.get(report.variety_id)
            updated = True

        if report.contractor_id:
            if report.contractor_id not in contractor_map:
                option = ReportDropdownOption.objects.filter(pk=report.contractor_id).first()
                if option:
                    contractor_obj, _ = Contractor.objects.get_or_create(
                        company=option.company,
                        name=option.name,
                        defaults={'rate_per_hour': 0, 'is_active': True},
                    )
                    contractor_map[option.pk] = contractor_obj.pk
            report.contractor_new_id = contractor_map.get(report.contractor_id)
            updated = True

        if report.unit_id:
            if report.unit_id not in unit_map:
                option = ReportDropdownOption.objects.filter(pk=report.unit_id).first()
                if option:
                    unit_obj, _ = Unit.objects.get_or_create(company=option.company, name=option.name)
                    unit_map[option.pk] = unit_obj.pk
            report.unit_new_id = unit_map.get(report.unit_id)
            updated = True

        if updated:
            report.save(update_fields=['variety_new_id', 'contractor_new_id', 'unit_new_id'])


def reverse_migrate_report_dropdown_options(apps, schema_editor):
    # No reverse migration because the old ReportDropdownOption relationships are preserved.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_remove_legacy_location_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='users.company')),
            ],
            options={
                'verbose_name': 'Variety',
                'verbose_name_plural': 'Varieties',
                'unique_together': {('company', 'name')},
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='users.company')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'unique_together': {('company', 'name')},
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dailytaskreport',
            name='variety_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_task_reports', to='reports.variety'),
        ),
        migrations.AddField(
            model_name='dailytaskreport',
            name='contractor_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_task_reports', to='reports.contractor'),
        ),
        migrations.AddField(
            model_name='dailytaskreport',
            name='unit_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_task_reports', to='reports.unit'),
        ),
        migrations.RunPython(migrate_report_dropdown_options, reverse_migrate_report_dropdown_options),
        migrations.RemoveField(
            model_name='dailytaskreport',
            name='variety',
        ),
        migrations.RemoveField(
            model_name='dailytaskreport',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='dailytaskreport',
            name='unit',
        ),
        migrations.RenameField(
            model_name='dailytaskreport',
            old_name='variety_new',
            new_name='variety',
        ),
        migrations.RenameField(
            model_name='dailytaskreport',
            old_name='contractor_new',
            new_name='contractor',
        ),
        migrations.RenameField(
            model_name='dailytaskreport',
            old_name='unit_new',
            new_name='unit',
        ),
        migrations.AlterField(
            model_name='dailytaskreport',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_task_reports', to='reports.variety'),
        ),
        migrations.AlterField(
            model_name='dailytaskreport',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_task_reports', to='reports.unit'),
        ),
    ]
