# Generated by GitHub Copilot on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_replace_reportdropdownoption_with_proper_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytaskreport',
            name='farm',
        ),
    ]
