# Generated by Django 6.0.4 on 2026-05-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_contractor_address_contractor_commercial_registry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('labor_supply', 'توريد عمالة'), ('equipment_rental', 'تأجير معدات'), ('general_contracting', 'مقاولات عامة'), ('specialized_services', 'خدمات متخصصة'), ('other', 'أخرى')], default='', max_length=50, verbose_name='نوع النشاط'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التعاقد'),
        ),
    ]
