# Generated by Django 6.0.4 on 2026-05-25 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_initial'),
        ('reports', '0013_add_contractor_contract_date_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizationreport',
            name='enclosure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fertilization_reports', to='farm.locationnode', verbose_name='الحوشة'),
        ),
    ]
