# Generated by Django 6.0.4 on 2026-06-02 18:56

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_fertilizationreport_enclosure'),
        ('users', '0008_farmsystemconfig'),
        ('warehouse', '0002_materialverificationalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestcontrolreport',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الكمية المستخدمة'),
        ),
        migrations.CreateModel(
            name='AppliedPesticide',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_pesticide_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المبيد الخارجي')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية المستخدمة')),
                ('rate_per_feddan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='معدل الاستخدام للفدان')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('pesticide_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.item', verbose_name='المبيد')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_pesticides', to='reports.pestcontrolreport')),
            ],
            options={
                'verbose_name': 'المبيد المستخدم',
                'verbose_name_plural': 'المبيدات المستخدمة',
                'db_table': 'applied_pesticides',
            },
        ),
    ]
