# Generated by Django 6.0.4 on 2026-04-29 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farm", "0010_work_location_to_fk"),
        (
            "reports",
            "0014_remove_dailytaskreport_reports_dai_crop_id_5c9ce8_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailytaskreport",
            name="work_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_task_work_reports",
                to="farm.locationnode",
                verbose_name="مكان العمل",
            ),
        ),
    ]
