# Generated by Django 6.0.4 on 2026-04-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_remove_dailytaskreport_reports_dai_crop_id_5c9ce8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytaskreport',
            name='work_location',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='مكان العمل'),
        ),
    ]
