# Generated by Django 6.0.4 on 2026-05-08 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0010_work_location_to_fk'),
        ('reports', '0015_alter_dailytaskreport_work_location'),
        ('users', '0005_company_user_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_workers', models.PositiveIntegerField(default=0, verbose_name='عمال الشركة')),
                ('contractor_workers', models.PositiveIntegerField(default=0, verbose_name='عمال المقاول')),
                ('actual_productivity', models.FloatField(blank=True, null=True, verbose_name='الانتاجية الفعلية')),
                ('work_hours', models.FloatField(default=0.0, verbose_name='ساعات العمل')),
                ('overtime_hours', models.FloatField(blank=True, null=True, verbose_name='ساعات الإضافي')),
                ('overtime_productivity', models.FloatField(blank=True, null=True, verbose_name='انتاجية الإضافي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_logs', to='reports.contractor', verbose_name='كود المقاول')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_logs', to='farm.locationnode')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.operation', verbose_name='العملية الفنية')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='reports.dailytaskreport', verbose_name='التقرير الحاوي')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_logs', to='reports.unit', verbose_name='الوحدة')),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_logs', to='reports.variety', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'سجل عملية',
                'verbose_name_plural': 'سجلات العمليات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='operation_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.operationlog'),
        ),
        migrations.AddField(
            model_name='laborentry',
            name='operation_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_entries', to='reports.operationlog'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['company', 'operation'], name='reports_ope_company_879fd1_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['company', 'location'], name='reports_ope_company_3bdff9_idx'),
        ),
    ]
