# Generated by Django 6.0.4 on 2026-06-02 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_alter_pestcontrolreport_quantity_appliedpesticide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationallocationallocation',
            name='allocated_workers_contractor_a',
        ),
        migrations.RemoveField(
            model_name='operationallocationallocation',
            name='allocated_workers_contractor_b',
        ),
    ]
