# Generated by Django 6.0.4 on 2026-06-02 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_remove_irrigationreport_contractor_workers_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationallocationallocation',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.contractor', verbose_name='المقاول'),
        ),
        migrations.AddField(
            model_name='operationallocationallocation',
            name='contractor_workers',
            field=models.IntegerField(default=0, verbose_name='عمال المقاول'),
        ),
    ]
