# Generated by Django 6.0.4 on 2026-05-09 04:35

from django.db import migrations


def forward_func(apps, schema_editor):
    DailyTaskReport = apps.get_model("reports", "DailyTaskReport")
    OperationLog = apps.get_model("reports", "OperationLog")
    LaborEntry = apps.get_model("reports", "LaborEntry")
    Attachment = apps.get_model("reports", "Attachment")

    # Safe backfill: Create an OperationLog for every DailyTaskReport
    for report in DailyTaskReport.objects.all().iterator():
        # update_or_create provides idempotency in case migration is run multiple times
        op_log, created = OperationLog.objects.update_or_create(
            report=report,
            defaults={
                "company_id": report.company_id,
                "location_id": report.location_id,
                "operation_id": report.operation_id,
                "variety_id": report.variety_id,
                "unit_id": report.unit_id,
                "contractor_id": report.contractor_id,
                "company_workers": report.company_workers,
                "contractor_workers": report.contractor_workers,
                "actual_productivity": report.actual_productivity,
                "work_hours": report.work_hours,
                "overtime_hours": report.overtime_hours,
                "overtime_productivity": report.overtime_productivity,
                "created_at": report.created_at,
            }
        )

        # Safely link children that haven't been linked yet
        LaborEntry.objects.filter(report=report, operation_log__isnull=True).update(operation_log=op_log)
        Attachment.objects.filter(report=report, operation_log__isnull=True).update(operation_log=op_log)


def reverse_func(apps, schema_editor):
    LaborEntry = apps.get_model("reports", "LaborEntry")
    Attachment = apps.get_model("reports", "Attachment")
    
    # Safely sever the bridge without deleting the containers
    LaborEntry.objects.update(operation_log=None)
    Attachment.objects.update(operation_log=None)
    # The OperationLogs will be dropped if the previous schema migration is rolled back,
    # so we don't strictly need to delete them here. It's safer to just unlink.


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_operationlog_attachment_operation_log_and_more'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
    ]
