# Generated by Django 6.0.4 on 2026-06-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_operationallocationallocation_contractor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedpesticide',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الكمية المستخدمة'),
        ),
    ]
