# Generated by Django 5.0.3 on 2026-05-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_backfill_operation_logs'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
                -- Drop legacy constraints
                ALTER TABLE reports_dailytaskreport DROP CONSTRAINT reports_dailytaskrep_contractor_id_6d666f33_fk_reports_r;
                ALTER TABLE reports_dailytaskreport DROP CONSTRAINT reports_dailytaskrep_unit_id_8f71a990_fk_reports_r;
                ALTER TABLE reports_dailytaskreport DROP CONSTRAINT reports_dailytaskrep_variety_id_51fe4c16_fk_reports_r;

                -- Add the missing contractor constraint
                ALTER TABLE reports_dailytaskreport ADD CONSTRAINT reports_dailytaskrep_contractor_id_fk_reports_contractor_id FOREIGN KEY (contractor_id) REFERENCES reports_contractor(id) DEFERRABLE INITIALLY DEFERRED;
            ''',
            reverse_sql='''
                -- Drop the corrected contractor constraint
                ALTER TABLE reports_dailytaskreport DROP CONSTRAINT reports_dailytaskrep_contractor_id_fk_reports_contractor_id;

                -- Restore legacy constraints
                ALTER TABLE reports_dailytaskreport ADD CONSTRAINT reports_dailytaskrep_contractor_id_6d666f33_fk_reports_r FOREIGN KEY (contractor_id) REFERENCES reports_reportdropdownoption(id) DEFERRABLE INITIALLY DEFERRED;
                ALTER TABLE reports_dailytaskreport ADD CONSTRAINT reports_dailytaskrep_unit_id_8f71a990_fk_reports_r FOREIGN KEY (unit_id) REFERENCES reports_reportdropdownoption(id) DEFERRABLE INITIALLY DEFERRED;
                ALTER TABLE reports_dailytaskreport ADD CONSTRAINT reports_dailytaskrep_variety_id_51fe4c16_fk_reports_r FOREIGN KEY (variety_id) REFERENCES reports_reportdropdownoption(id) DEFERRABLE INITIALLY DEFERRED;
            '''
        )
    ]
