# Generated by Django 6.0.4 on 2026-05-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_fix_dailytaskreport_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytaskreport',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='سبب الرفض'),
        ),
        migrations.AddField(
            model_name='dailytaskreport',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مقدم'), ('under_review', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='draft', max_length=20, verbose_name='حالة التقرير'),
        ),
    ]
