# Generated by Django 6.0.4 on 2026-06-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_alter_appliedpesticide_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestcontrolreport',
            name='date',
            field=models.DateTimeField(verbose_name='التاريخ'),
        ),
    ]
