# Generated by Django 6.0.4 on 2026-06-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_alter_pestcontrolreport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='allow_over_coverage',
            field=models.BooleanField(default=False, verbose_name='السماح بتجاوز 100%'),
        ),
        migrations.AddField(
            model_name='operation',
            name='coverage_type',
            field=models.CharField(choices=[('TREE_BASED', 'Tree Based'), ('AREA_BASED', 'Area Based'), ('EVENT_BASED', 'Event Based'), ('TIME_BASED', 'Time Based'), ('PRODUCTION_BASED', 'Production Based')], default='TIME_BASED', max_length=50, verbose_name='نوع التغطية'),
        ),
        migrations.AddField(
            model_name='operation',
            name='repeatable',
            field=models.BooleanField(default=True, verbose_name='قابلة للتكرار'),
        ),
    ]
