# Generated by Django 6.0.4 on 2026-05-09 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_add_dailytaskreport_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytaskreport',
            name='override_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت التعديل الاستثنائي'),
        ),
        migrations.AddField(
            model_name='dailytaskreport',
            name='override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_reports', to=settings.AUTH_USER_MODEL, verbose_name='المعدل الاستثنائي'),
        ),
        migrations.AddField(
            model_name='dailytaskreport',
            name='override_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب التعديل'),
        ),
        migrations.AddField(
            model_name='dailytaskreport',
            name='was_overridden',
            field=models.BooleanField(default=False, verbose_name='تم تعديله استثنائياً'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب'),
        ),
    ]
