# Generated by Django 6.0.4 on 2026-05-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_dailytaskreport_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailytaskreport',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'تقرير مهام يومي', 'verbose_name_plural': 'تقارير المهام اليومية'},
        ),
        migrations.AddField(
            model_name='dailytaskreport',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد'),
        ),
        migrations.AddField(
            model_name='dailytaskreport',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرفض'),
        ),
        migrations.AddField(
            model_name='dailytaskreport',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التقديم'),
        ),
        migrations.AddField(
            model_name='dailytaskreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
    ]
