# Generated by Django 6.0.4 on 2026-05-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_alter_dailytaskreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operation',
            name='profile_type',
            field=models.CharField(default='generic', max_length=50),
        ),
        migrations.AddField(
            model_name='operation',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='profile_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='profile_type',
            field=models.CharField(default='generic', max_length=50),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='profile_version',
            field=models.IntegerField(default=1),
        ),
    ]
