# Generated by Django 6.0.4 on 2026-05-09 12:46

from django.db import migrations

def seed_system_operations(apps, schema_editor):
    Operation = apps.get_model('reports', 'Operation')
    Company = apps.get_model('users', 'Company')
    
    companies = Company.objects.all()
    
    system_ops = [
        {"name": "ري", "slug": "irrigation", "profile_type": "irrigation", "category": "other", "is_system": True},
        {"name": "تسميد", "slug": "fertilization", "profile_type": "fertilization", "category": "fertilization", "is_system": True},
        {"name": "رش", "slug": "spraying", "profile_type": "spraying", "category": "protection", "is_system": True},
    ]
    
    for company in companies:
        for op in system_ops:
            Operation.objects.get_or_create(
                company=company,
                slug=op["slug"],
                defaults={
                    "name": op["name"],
                    "profile_type": op["profile_type"],
                    "category": op["category"],
                    "is_system": op["is_system"],
                    "is_active": True
                }
            )

def reverse_seed(apps, schema_editor):
    Operation = apps.get_model('reports', 'Operation')
    Operation.objects.filter(is_system=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_operation_is_system_operation_profile_type_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_system_operations, reverse_seed),
    ]
