# Generated by Django 6.0.4 on 2026-05-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_seed_system_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variety',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
