# Generated by Django 6.0.4 on 2026-05-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_unit_is_active_variety_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='json_schema',
            field=models.JSONField(blank=True, help_text='JSON Schema (Draft-7) rules for validating profile_data', null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='schema_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='operation',
            name='ui_schema',
            field=models.JSONField(blank=True, help_text='UI definitions for rendering forms and timeline fields', null=True),
        ),
    ]
