# Generated by Django 6.0.4 on 2026-05-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_operationlog_deleted_at_operationlog_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='bulk_operation_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='operation_scope',
            field=models.CharField(choices=[('SINGLE', 'Single Enclosure'), ('STAGE', 'Stage Bulk'), ('SECTOR', 'Sector Bulk'), ('FARM', 'Farm Bulk')], default='SINGLE', max_length=20),
        ),
    ]
