# Generated by Django 6.0.4 on 2026-05-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0028_operationlog_bulk_operation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('COMPLETED', 'تم التنفيذ'), ('FAILED', 'فشل التنفيذ'), ('SKIPPED', 'تم التخطي')], default='COMPLETED', max_length=20),
        ),
    ]
