# Generated by Django 6.0.4 on 2026-05-09 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0013_alter_enclosureprofile_company_alter_farm_company_and_more'),
        ('reports', '0029_operationlog_status'),
        ('users', '0006_apppermission_user_app_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Labor Category',
                'verbose_name_plural': 'Labor Categories',
            },
        ),
        migrations.CreateModel(
            name='PackagingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Packaging Type',
                'verbose_name_plural': 'Packaging Types',
            },
        ),
        migrations.CreateModel(
            name='ProductivityClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Productivity Classification',
                'verbose_name_plural': 'Productivity Classifications',
            },
        ),
        migrations.CreateModel(
            name='QualityGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Quality Grade',
                'verbose_name_plural': 'Quality Grades',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'مفتوح'), ('CLOSED', 'مغلق'), ('ARCHIVED', 'مؤرشف')], default='OPEN', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'موسم',
                'verbose_name_plural': 'المواسم',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SortingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sorting Category',
                'verbose_name_plural': 'Sorting Categories',
            },
        ),
        migrations.RemoveIndex(
            model_name='operationlog',
            name='reports_ope_company_879fd1_idx',
        ),
        migrations.RemoveIndex(
            model_name='operationlog',
            name='reports_ope_company_3bdff9_idx',
        ),
        migrations.AddField(
            model_name='operationlog',
            name='chain_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='كود السلسلة'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='parent_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_logs', to='reports.operationlog', verbose_name='العملية الأب'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='source_type',
            field=models.CharField(blank=True, choices=[('DAILY_TASK', 'Daily Task Report'), ('HARVEST', 'Harvest Report'), ('SORTING', 'Sorting Report')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AlterField(
            model_name='dailytaskreport',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AlterField(
            model_name='laborentry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='reports.dailytaskreport', verbose_name='التقرير الحاوي'),
        ),
        migrations.AddField(
            model_name='laborcategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='packagingtype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='productivityclassification',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='qualitygrade',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='season',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_logs', to='reports.season'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['company', 'operation', 'created_at'], name='reports_ope_company_b15b18_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['company', 'location', 'created_at'], name='reports_ope_company_046f3b_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['source_type', 'source_id'], name='reports_ope_source__46f3a3_idx'),
        ),
        migrations.AddField(
            model_name='sortingcategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.RemoveField(
            model_name='operationlog',
            name='operation_scope',
        ),
        migrations.AlterUniqueTogether(
            name='laborcategory',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='packagingtype',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='productivityclassification',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='qualitygrade',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='sortingcategory',
            unique_together={('company', 'name')},
        ),
    ]
