# Generated by Django 6.0.4 on 2026-05-20 19:01

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_landingcontent_about_text_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('specifications', models.TextField(blank=True, default='')),
                ('current_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('oil_change_interval_hours', models.DecimalField(decimal_places=2, default=250.0, max_digits=8)),
                ('oil_change_interval_days', models.IntegerField(default=180)),
                ('last_oil_change_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_oil_change_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('maintenance_type', models.CharField(default='scheduled', max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='equipment.equipment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OilChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('hours_at_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('oil_type', models.CharField(blank=True, default='', max_length=100)),
                ('filter_changed', models.BooleanField(default=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oil_changes', to='equipment.equipment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('hours_used', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fuel_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('operator', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='equipment.equipment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
