# Generated by Django 6.0.4 on 2026-05-27 06:08

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('users', '0007_user_avatar_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'المعدات والآليات'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='current_meter',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='قراءة العداد الحالية'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('tractor', 'جرار / حارث زراعي'), ('car', 'سيارة نقل / بيك أب'), ('motorcycle', 'موتوسيكل ميداني'), ('generator', 'مولد كهربائي / مضخة ري'), ('sprayer', 'ماكينة رش / مكافحة')], default='tractor', max_length=50, verbose_name='نوع المعدة'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط بالخدمة'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_maintenance_meter',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='قراءة العداد عند آخر صيانة'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='maintenance_interval',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='فترة الصيانة الدورية المسموحة'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='meter_type',
            field=models.CharField(choices=[('hours', 'ساعات عمل (Hours)'), ('km', 'مسافة مقطوعة (KM)')], default='hours', max_length=20, verbose_name='وحدة قياس العداد'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات المواصفات'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='plate_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم اللوحة / شاسيه'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم المعدة / الآلية'),
        ),
        migrations.AlterModelTable(
            name='equipment',
            table='fleet_equipment',
        ),
        migrations.CreateModel(
            name='EquipmentLog',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_type', models.CharField(choices=[('maintenance', 'إصلاح وصيانة عامة'), ('oil_change', 'تغيير زيت وفلاتر'), ('fueling', 'تزويد وقود ومحروقات')], max_length=30, verbose_name='نوع الحركة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('meter_reading', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قراءة العداد أثناء العملية')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='التكلفة المباشرة (توثيق)')),
                ('details', models.TextField(verbose_name='تفاصيل الحركة والبيانات المدخلة')),
                ('assigned_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_operations', to=settings.AUTH_USER_MODEL, verbose_name='السائق / المستخدم المسؤول')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='equipment.equipment', verbose_name='المعدة')),
            ],
            options={
                'db_table': 'fleet_equipment_logs',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FleetMaintenanceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_message', models.CharField(max_length=500)),
                ('is_resolved', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_alerts', to='equipment.equipment')),
            ],
            options={
                'db_table': 'fleet_maintenance_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
