# Generated by Django 6.0.4 on 2026-05-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_options_equipment_current_meter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ آخر صيانة'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='meter_type',
            field=models.CharField(choices=[('hours', 'ساعات عمل (Hours)'), ('km', 'مسافة مقطوعة (KM)'), ('days', 'أيام تقويمية (Days)')], default='hours', max_length=20, verbose_name='وحدة قياس العداد'),
        ),
    ]
