# Generated by Django 6.0.4 on 2026-05-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_last_maintenance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentlog',
            name='amount_liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='كمية اللترات (وقود / زيت)'),
        ),
    ]
