# Generated by Django 6.0.4 on 2026-05-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipmentlog_amount_liters'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='equipment_images/', verbose_name='صورة المعدة'),
        ),
    ]
