# Generated by Django 6.0.4 on 2026-05-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='رابط صورة المعدة'),
        ),
    ]
