# Generated by Django 6.0.4 on 2026-05-16 17:55

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnclosureProfile',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_type', models.CharField(blank=True, max_length=50, null=True)),
                ('planting_year', models.PositiveIntegerField(blank=True, null=True)),
                ('tree_count', models.PositiveIntegerField(default=0)),
                ('seedling_count', models.PositiveIntegerField(default=0)),
                ('expected_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profile_data', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('general_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات عامة')),
            ],
            options={
                'verbose_name': 'Enclosure Profile',
                'verbose_name_plural': 'Enclosure Profiles',
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FarmSettings',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enable_sector', models.BooleanField(default=True)),
                ('enable_stage', models.BooleanField(default=True)),
                ('enable_enclosure', models.BooleanField(default=True)),
                ('allow_stage_without_sector', models.BooleanField(default=False)),
                ('allow_enclosure_without_stage', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Farm Settings',
            },
        ),
        migrations.CreateModel(
            name='LocationNode',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('STAGE', 'Stage'), ('SECTOR', 'Sector'), ('ENCLOSURE', 'Enclosure')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'ordering': ['order', 'created_at', 'id'],
            },
        ),
    ]
