# Generated by Django 6.0.4 on 2026-05-16 17:55

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enclosureprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='farm',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='farmsettings',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='farmsettings',
            name='farm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='farm.farm'),
        ),
        migrations.AddField(
            model_name='locationnode',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='locationnode',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_nodes', to='farm.farm'),
        ),
        migrations.AddField(
            model_name='locationnode',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='farm.locationnode'),
        ),
        migrations.AddField(
            model_name='enclosureprofile',
            name='location_node',
            field=models.OneToOneField(limit_choices_to={'type': 'ENCLOSURE'}, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='farm.locationnode'),
        ),
        migrations.AddIndex(
            model_name='locationnode',
            index=models.Index(fields=['company', 'type', 'is_active'], name='farm_locati_company_b69a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='locationnode',
            index=models.Index(fields=['farm', 'type', 'is_active'], name='farm_locati_farm_id_afeb61_idx'),
        ),
        migrations.AddIndex(
            model_name='locationnode',
            index=models.Index(fields=['parent', 'is_active'], name='farm_locati_parent__428083_idx'),
        ),
        migrations.AddIndex(
            model_name='locationnode',
            index=models.Index(fields=['tree_id', 'lft'], name='farm_locationnode_tree_id_8c8a'),
        ),
        migrations.AddConstraint(
            model_name='locationnode',
            constraint=models.UniqueConstraint(fields=('company', 'farm', 'parent', 'name', 'type'), name='uniq_location_node_per_parent'),
        ),
    ]
