# Generated by Django 6.0.4 on 2026-06-04 18:15

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_initial'),
        ('users', '0008_farmsystemconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageProfile',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tree_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('general_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات عامة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('location_node', models.OneToOneField(limit_choices_to={'type': 'STAGE'}, on_delete=django.db.models.deletion.CASCADE, related_name='stage_profile', to='farm.locationnode')),
            ],
            options={
                'verbose_name': 'Stage Profile',
                'verbose_name_plural': 'Stage Profiles',
            },
        ),
    ]
