# Generated by Django 6.0.4 on 2026-04-29 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "farm",
            "0007_rename_farm_locati_company_aeab7b_idx_farm_locati_company_b69a3e_idx_and_more",
        ),
        ("users", "0005_company_user_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enable_sector", models.BooleanField(default=True)),
                ("enable_stage", models.BooleanField(default=True)),
                ("enable_enclosure", models.BooleanField(default=True)),
                ("allow_stage_without_sector", models.BooleanField(default=False)),
                ("allow_enclosure_without_stage", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.company"
                    ),
                ),
                (
                    "farm",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="farm.farm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Settings",
            },
        ),
    ]
