# Generated by Django 6.0.4 on 2026-04-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farm", "0008_add_farm_settings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="locationnode",
            options={"ordering": ["order", "created_at", "id"]},
        ),
        migrations.AddField(
            model_name="locationnode",
            name="offshoot_count",
            field=models.IntegerField(blank=True, help_text="عدد الفسائل", null=True),
        ),
        migrations.AddField(
            model_name="locationnode",
            name="palm_count",
            field=models.IntegerField(
                blank=True, help_text="عدد النخيل في الحوشة", null=True
            ),
        ),
        migrations.AddField(
            model_name="locationnode",
            name="planting_date",
            field=models.DateField(blank=True, help_text="تاريخ الزراعة", null=True),
        ),
        migrations.AddField(
            model_name="locationnode",
            name="production_tons",
            field=models.FloatField(
                blank=True, help_text="كمية الإنتاج بالطن", null=True
            ),
        ),
    ]
