# Generated by Django 6.0.4 on 2026-04-29 21:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("farm", "0009_alter_locationnode_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locationnode",
            name="offshoot_count",
        ),
        migrations.RemoveField(
            model_name="locationnode",
            name="palm_count",
        ),
        migrations.RemoveField(
            model_name="locationnode",
            name="planting_date",
        ),
        migrations.RemoveField(
            model_name="locationnode",
            name="production_tons",
        ),
    ]
