# Generated by Django 6.0.4 on 2026-05-09 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0010_work_location_to_fk'),
        ('users', '0006_apppermission_user_app_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnclosureProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(blank=True, max_length=50, null=True)),
                ('planting_year', models.PositiveIntegerField(blank=True, null=True)),
                ('tree_count', models.PositiveIntegerField(default=0)),
                ('seedling_count', models.PositiveIntegerField(default=0)),
                ('expected_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profile_data', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('location_node', models.OneToOneField(limit_choices_to={'type': 'ENCLOSURE'}, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='farm.locationnode')),
            ],
            options={
                'verbose_name': 'Enclosure Profile',
                'verbose_name_plural': 'Enclosure Profiles',
            },
        ),
    ]
