# Generated by Django 6.0.4 on 2026-05-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0011_enclosureprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="enclosureprofile",
            name="general_notes",
            field=models.TextField(blank=True, null=True, verbose_name="ملاحظات عامة"),
        ),
    ]
