# Generated by Django 6.0.4 on 2026-05-16 17:55

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='harvest/attachments/%Y/%m/%d/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HarvestReport',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('harvest_date', models.DateField(verbose_name='تاريخ الحصاد')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية المحصودة')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مقدم'), ('APPROVED', 'معتمد'), ('FINALIZED', 'نهائي - مقفل')], default='DRAFT', max_length=20)),
                ('is_partial', models.BooleanField(default=False, verbose_name='حصاد جزئي')),
                ('labor_count', models.PositiveIntegerField(default=0, verbose_name='إجمالي عدد العمال')),
                ('company_workers', models.PositiveIntegerField(default=0, verbose_name='عمال الشركة')),
                ('contractor_workers', models.PositiveIntegerField(default=0, verbose_name='عمال المقاول')),
                ('contractor_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المقاول')),
                ('labor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='ساعات العمل')),
                ('transport_method', models.TextField(blank=True, verbose_name='طريقة النقل / معلومات النقل')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='التكلفة التقديرية')),
                ('variety_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('unit_label_snapshot', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تقرير حصاد',
                'verbose_name_plural': 'تقارير الحصاد',
                'ordering': ['-harvest_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SortingReport',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_date', models.DateField(verbose_name='تاريخ الفرز')),
                ('incoming_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية الواردة')),
                ('final_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية المقبولة')),
                ('rejected_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الكمية المرفوضة')),
                ('waste_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='هالك / فاقد')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مقدم'), ('FINALIZED', 'نهائي - مقفل')], default='DRAFT', max_length=20)),
                ('harvest_info_snapshot', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تقرير فرز',
                'verbose_name_plural': 'تقارير الفرز',
                'ordering': ['-processing_date'],
            },
        ),
        migrations.CreateModel(
            name='AnnualYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('production_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_yields', to='farm.locationnode')),
            ],
        ),
    ]
