# Generated by Django 6.0.4 on 2026-05-16 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0002_initial'),
        ('production', '0001_initial'),
        ('reports', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestattachment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='harvestreport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='harvestreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_harvests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='harvestreport',
            name='location',
            field=models.ForeignKey(limit_choices_to={'type': 'ENCLOSURE'}, on_delete=django.db.models.deletion.PROTECT, related_name='harvest_reports', to='farm.locationnode'),
        ),
        migrations.AddField(
            model_name='harvestreport',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvest_reports', to='reports.season'),
        ),
        migrations.AddField(
            model_name='harvestreport',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_harvests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='harvestreport',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvest_reports', to='reports.unit'),
        ),
        migrations.AddField(
            model_name='harvestreport',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvest_reports', to='reports.variety'),
        ),
        migrations.AddField(
            model_name='harvestattachment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='production.harvestreport'),
        ),
        migrations.AddField(
            model_name='sortingreport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='sortingreport',
            name='harvest_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorting_reports', to='production.harvestreport', verbose_name='تقرير الحصاد المرتبط'),
        ),
        migrations.AddField(
            model_name='sortingreport',
            name='quality_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.qualitygrade'),
        ),
        migrations.AddField(
            model_name='sortingreport',
            name='sorting_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.sortingcategory'),
        ),
        migrations.AddConstraint(
            model_name='annualyield',
            constraint=models.UniqueConstraint(fields=('plot', 'year'), name='unique_plot_year_yield'),
        ),
        migrations.AddIndex(
            model_name='harvestreport',
            index=models.Index(fields=['company', 'location', 'season'], name='production__company_c9e855_idx'),
        ),
        migrations.AddIndex(
            model_name='harvestreport',
            index=models.Index(fields=['status'], name='production__status_d840e6_idx'),
        ),
    ]
