# Generated by Django 6.0.4 on 2026-05-09 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0013_alter_enclosureprofile_company_alter_farm_company_and_more'),
        ('production', '0001_initial'),
        ('reports', '0030_laborcategory_packagingtype_and_more'),
        ('users', '0006_apppermission_user_app_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualyield',
            name='plot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_yields', to='farm.locationnode'),
        ),
        migrations.CreateModel(
            name='HarvestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField(verbose_name='تاريخ الحصاد')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية المحصودة')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مقدم'), ('APPROVED', 'معتمد'), ('FINALIZED', 'نهائي - مقفل')], default='DRAFT', max_length=20)),
                ('is_partial', models.BooleanField(default=False, verbose_name='حصاد جزئي')),
                ('labor_count', models.PositiveIntegerField(default=0, verbose_name='عدد العمال')),
                ('labor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='ساعات العمل')),
                ('transportation_info', models.TextField(blank=True, verbose_name='معلومات النقل')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='التكلفة التقديرية')),
                ('variety_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('unit_label_snapshot', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('location', models.ForeignKey(limit_choices_to={'type': 'ENCLOSURE'}, on_delete=django.db.models.deletion.PROTECT, related_name='harvest_reports', to='farm.locationnode')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvest_reports', to='reports.season')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_harvests', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvest_reports', to='reports.unit')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvest_reports', to='reports.variety')),
            ],
            options={
                'verbose_name': 'تقرير حصاد',
                'verbose_name_plural': 'تقارير الحصاد',
                'ordering': ['-harvest_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SortingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_date', models.DateField(verbose_name='تاريخ الفرز')),
                ('incoming_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية الواردة')),
                ('final_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية المقبولة')),
                ('rejected_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الكمية المرفوضة')),
                ('waste_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='هالك / فاقد')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مقدم'), ('FINALIZED', 'نهائي - مقفل')], default='DRAFT', max_length=20)),
                ('harvest_info_snapshot', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('harvest_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorting_reports', to='production.harvestreport', verbose_name='تقرير الحصاد المرتبط')),
                ('quality_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.qualitygrade')),
                ('sorting_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.sortingcategory')),
            ],
            options={
                'verbose_name': 'تقرير فرز',
                'verbose_name_plural': 'تقارير الفرز',
                'ordering': ['-processing_date'],
            },
        ),
        migrations.AddIndex(
            model_name='harvestreport',
            index=models.Index(fields=['company', 'location', 'season'], name='production__company_c9e855_idx'),
        ),
        migrations.AddIndex(
            model_name='harvestreport',
            index=models.Index(fields=['status'], name='production__status_d840e6_idx'),
        ),
    ]
