# Generated by Django 6.0.4 on 2026-05-20 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestreport',
            name='override_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harvestreport',
            name='override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_harvests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='harvestreport',
            name='override_reason',
            field=models.TextField(blank=True, verbose_name='سبب التعديل الاستثنائي'),
        ),
        migrations.AddField(
            model_name='harvestreport',
            name='was_overridden',
            field=models.BooleanField(default=False),
        ),
    ]
