# Generated by Django 6.0.4 on 2026-05-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_harvestreport_override_at_harvestreport_override_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvestattachment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='harvestattachment',
            name='file_name',
        ),
        migrations.AddField(
            model_name='harvestattachment',
            name='file_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='harvestattachment',
            name='file_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('FILE', 'File')], default='IMAGE', max_length=20),
        ),
    ]
