# Generated by Django 6.0.4 on 2026-05-17 21:04

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_initial'),
        ('reports', '0003_alter_customfieldvalue_object_id'),
        ('users', '0004_landingcontent_about_text_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الراتب الشهري'),
        ),
        migrations.AddField(
            model_name='employee',
            name='standard_work_hours',
            field=models.PositiveIntegerField(default=8, verbose_name='ساعات العمل القياسية'),
        ),
        migrations.CreateModel(
            name='ContractorLedger',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('transaction_type', models.CharField(choices=[('EARNING', 'مستحقات عمل'), ('OVERTIME', 'إضافي ساعات'), ('DEDUCTION', 'خصومات ساعات'), ('PAYMENT', 'دفعة مسددة للمقاول')], max_length=20, verbose_name='نوع الحركة')),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='عدد الساعات')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر الساعة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='reports.contractor', verbose_name='المقاول')),
                ('labor_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_ledger_entries', to='reports.laborentry', verbose_name='بند العمالة المصدر')),
            ],
            options={
                'verbose_name': 'دفتر أستاذ المقاول',
                'verbose_name_plural': 'دفاتر أستاذ المقاولين',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفترة')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('is_closed', models.BooleanField(default=False, verbose_name='مغلقة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
            options={
                'verbose_name': 'فترة الرواتب',
                'verbose_name_plural': 'فترات الرواتب',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='اسم العامل بالكامل')),
                ('worker_type', models.CharField(choices=[('COMPANY', 'عامل شركة'), ('CONTRACTOR', 'عامل مقاول')], default='COMPANY', max_length=20)),
                ('badge_number', models.CharField(blank=True, default='', max_length=50, verbose_name='رقم البادج / الكود')),
                ('national_id', models.CharField(blank=True, default='', max_length=50, verbose_name='الرقم القومي')),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الراتب الشهري')),
                ('standard_work_hours', models.PositiveIntegerField(default=8, verbose_name='ساعات العمل القياسية اليومية')),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('terminated', 'Terminated')], default='active', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_workers', to='reports.contractor', verbose_name='المقاول التابع له')),
            ],
            options={
                'verbose_name': 'عامل ميداني',
                'verbose_name_plural': 'العمال الميدانيون',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PendingWorkerReview',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker_name_fallback', models.CharField(max_length=120, verbose_name='الاسم المكتوب يدوياً')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False, verbose_name='تم حلها')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('labor_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_review', to='reports.laborentry', verbose_name='بند العمالة المرتبط')),
                ('resolved_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reviews', to='hr.worker', verbose_name='العامل الذي تم ربطه')),
            ],
            options={
                'verbose_name': 'مراجعة عامل معلق',
                'verbose_name_plural': 'مراجعات العمال المعلقين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('transaction_type', models.CharField(choices=[('OVERTIME', 'عمل إضافي'), ('DEDUCTION', 'خصم ساعات')], max_length=20, verbose_name='نوع الحركة')),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='عدد الساعات')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المالي')),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('labor_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_transactions', to='reports.laborentry', verbose_name='بند العمالة المصدر')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='hr.payrollperiod', verbose_name='فترة الرواتب')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_transactions', to='hr.worker', verbose_name='العامل')),
            ],
            options={
                'verbose_name': 'حركة مالية للراتب',
                'verbose_name_plural': 'حركات مالية للرواتب',
                'ordering': ['-date'],
            },
        ),
    ]
