# Generated by Django 6.0.4 on 2026-05-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employee_monthly_salary_employee_standard_work_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='worker',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بدء العمل'),
        ),
    ]
