# Generated by Django 6.0.4 on 2026-05-18 19:50

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_worker_address_worker_hire_date'),
        ('users', '0004_landingcontent_about_text_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('national_id', 'بطاقة الرقم القومي'), ('academic_degree', 'شهادة التخرج/الشهادة الأكاديمية'), ('training_cert', 'شهادات الدورات والتدريب'), ('contract', 'عقد العمل المبرم')], max_length=30, verbose_name='نوع المستند')),
                ('document_file', models.FileField(upload_to='hr/employee_docs/', verbose_name='ملف المستند')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإصدار')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('is_verified', models.BooleanField(default=False, verbose_name='معتمد من الإدارة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'وثيقة موظف',
                'verbose_name_plural': 'وثائق الموظفين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollComponent',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('ALLOWANCE', 'بدل إضافي'), ('DEDUCTION', 'استقطاع / خصم ثابت')], max_length=20, verbose_name='نوع البند')),
                ('name', models.CharField(max_length=100, verbose_name='اسم البند (مثال: بدل انتقالات)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='القيمة المالية')),
                ('is_recurring', models.BooleanField(default=True, verbose_name='يتكرر شهرياً تلقائياً')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_components', to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'مكون مالي للراتب',
                'verbose_name_plural': 'مكونات الرواتب التفصيلية',
            },
        ),
    ]
