# Generated by Django 6.0.4 on 2026-05-16 17:55

import django.db.models.deletion
import django.utils.timezone
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="e.g. 'reports.override', 'reports.delete'", max_length=100, unique=True)),
                ('name', models.CharField(help_text="e.g. 'Can Override Reports'", max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'صلاحية مخصصة',
                'verbose_name_plural': 'صلاحيات مخصصة',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subscription_plan', models.CharField(default='starter', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LandingContent',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_title_en', models.CharField(default='Precision Agriculture, Redefined.', max_length=255)),
                ('hero_title_ar', models.CharField(default='الزراعة الدقيقة، أعيد تعريفها.', max_length=255)),
                ('hero_text_en', models.TextField(default='Seamlessly manage Palm and Olive field structures.')),
                ('hero_text_ar', models.TextField(default='إدارة مجالات النخيل والزيتون بسلاسة تامة.')),
                ('palm_text_en', models.TextField(default='Track Every Mother Tree & Offshoot.')),
                ('palm_text_ar', models.TextField(default='تتبع كل شجرة أم و فسيلة.')),
                ('olive_text_en', models.TextField(default='Synchronized Harvest Operations.')),
                ('olive_text_ar', models.TextField(default='عمليات حصاد متزامنة.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('ENGINEER', 'Engineer'), ('ACCOUNTANT', 'Accountant'), ('HR', 'HR'), ('WAREHOUSE', 'Warehouse')], max_length=20)),
                ('phones', models.JSONField(blank=True, default=list)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('app_permissions', models.ManyToManyField(blank=True, related_name='users', to='users.apppermission', verbose_name='صلاحيات مخصصة')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.company')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_ar', models.CharField(max_length=255)),
                ('message_en', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('user_pending', 'User Pending Approval'), ('low_stock', 'Low Stock Alert'), ('invoice', 'New Invoice'), ('leave_request', 'Leave Request'), ('system', 'System Notification')], default='system', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, default='', max_length=200)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
