# Generated by Django 6.0.4 on 2026-05-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingcontent',
            name='logo_text_ar',
            field=models.CharField(default='أطلس سيوة', max_length=100),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='logo_text_en',
            field=models.CharField(default='Atlas Farm', max_length=100),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='logo_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
