# Generated by Django 6.0.4 on 2026-05-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_landingcontent_logo_text_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingcontent',
            name='about_text_ar',
            field=models.TextField(default='تم تصميم نظام أطلس الزراعي الموحد ليقود ثورة تكنولوجية في أتمتة وتحليل بيانات المزارع الكبيرة. يساعدك محركنا الذكي على مراقبة الأشجار والإنتاجية وجدولة المهام والأسطول في مكان واحد.'),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='about_text_en',
            field=models.TextField(default='Atlas ERP empowers large-scale agricultural enterprises to register layout elements, tracks trees individually, structures daily engineer reporting sheets, and automates continuous yield metrics.'),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='about_title_ar',
            field=models.CharField(default='نظام أطلس لإدارة حقول النخيل والزيتون الدقيقة', max_length=255),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='about_title_en',
            field=models.CharField(default='Precision Farming Redefined', max_length=255),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='contact_email',
            field=models.CharField(default='info@atlasfarm.dz', max_length=100),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='contact_phone',
            field=models.CharField(default='+213 (0) 5XX XXX XXX', max_length=100),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='contact_text_ar',
            field=models.TextField(default='تواصل معنا الآن للحصول على استشارة كاملة لربط مزارعك وهيكلها وتجهيز لوحة التحكم المخصصة لشركتك.'),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='contact_text_en',
            field=models.TextField(default='Sign up today to configure your companies, isolate records, and launch dynamic daily reporting tools.'),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='contact_title_ar',
            field=models.CharField(default='ابدأ في رقمنة وأتمتة مزارعك اليوم', max_length=255),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='contact_title_en',
            field=models.CharField(default='Ready to Transform Your Operations?', max_length=255),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='features_title_ar',
            field=models.CharField(default='ما الذي يجعل أطلس الأفضل لإدارة مزارعك؟', max_length=255),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='features_title_en',
            field=models.CharField(default='Why Choose Atlas ERP for Your Agriculture?', max_length=255),
        ),
    ]
