# Generated by Django 6.0.4 on 2026-05-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_company_user_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="e.g. 'reports.override', 'reports.delete'", max_length=100, unique=True)),
                ('name', models.CharField(help_text="e.g. 'Can Override Reports'", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'صلاحية مخصصة',
                'verbose_name_plural': 'صلاحيات مخصصة',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='app_permissions',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.apppermission', verbose_name='صلاحيات مخصصة'),
        ),
    ]
