# Generated by Django 6.0.4 on 2026-05-27 07:49

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmSystemConfig',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm_name', models.CharField(default='مزرعة أطلس النموذجية', max_length=255)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('primary_color', models.CharField(default='#1E3A1E', max_length=50)),
                ('accent_color', models.CharField(default='#D4AF37', max_length=50)),
                ('currency', models.CharField(default='جنية مصري', max_length=20)),
                ('active_font', models.CharField(default='Cairo', max_length=50)),
                ('feature_accounting', models.BooleanField(default=True, verbose_name='نظام المحاسبة')),
                ('feature_hr', models.BooleanField(default=True, verbose_name='نظام الموارد البشرية HR')),
                ('feature_fleet', models.BooleanField(default=True, verbose_name='منظومة الأسطول والمعدات')),
                ('feature_warehouse', models.BooleanField(default=True, verbose_name='إدارة المخازن والمستودع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
            options={
                'verbose_name': 'إعدادات النظام والمزرعة',
                'db_table': 'farm_system_configs',
            },
        ),
    ]
