# Generated by Django 6.0.4 on 2026-05-24 21:42

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_avatar_url'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialVerificationAlert',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_report_type', models.CharField(choices=[('irrigation', 'ري'), ('pest_control', 'مكافحة')], max_length=50)),
                ('source_report_id', models.UUIDField()),
                ('suggested_name', models.CharField(max_length=255, verbose_name='الاسم المكتوب ميدانياً')),
                ('is_resolved', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('mapped_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.item', verbose_name='المادة المربوطة بالمستودع')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'warehouse_material_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
