
import os
import django
from django.db import connection

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')
django.setup()

def fix_db():
    queries = [
        # Create reports_variety
        """CREATE TABLE IF NOT EXISTS "reports_variety" (
            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
            "name" varchar(100) NOT NULL, 
            "company_id" bigint NOT NULL
        );""",
        """ALTER TABLE "reports_variety" ADD CONSTRAINT "reports_variety_company_id_name_0f57421f_uniq" UNIQUE ("company_id", "name");""",
        """ALTER TABLE "reports_variety" ADD CONSTRAINT "reports_variety_company_id_6e97d6e0_fk_users_company_id" FOREIGN KEY ("company_id") REFERENCES "users_company" ("id") DEFERRABLE INITIALLY DEFERRED;""",
        """CREATE INDEX IF NOT EXISTS "reports_variety_company_id_6e97d6e0" ON "reports_variety" ("company_id");""",
        
        # Create reports_unit
        """CREATE TABLE IF NOT EXISTS "reports_unit" (
            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
            "name" varchar(100) NOT NULL, 
            "company_id" bigint NOT NULL
        );""",
        """ALTER TABLE "reports_unit" ADD CONSTRAINT "reports_unit_company_id_name_9c55e132_uniq" UNIQUE ("company_id", "name");""",
        """ALTER TABLE "reports_unit" ADD CONSTRAINT "reports_unit_company_id_ec8cd84d_fk_users_company_id" FOREIGN KEY ("company_id") REFERENCES "users_company" ("id") DEFERRABLE INITIALLY DEFERRED;""",
        """CREATE INDEX IF NOT EXISTS "reports_unit_company_id_ec8cd84d" ON "reports_unit" ("company_id");""",
        
        # Re-add foreign keys to dailytaskreport if they are missing
        # variety_id
        """ALTER TABLE "reports_dailytaskreport" DROP CONSTRAINT IF EXISTS "reports_dailytaskrep_variety_id_51fe4c16_fk_reports_v";""",
        """ALTER TABLE "reports_dailytaskreport" ADD CONSTRAINT "reports_dailytaskrep_variety_id_51fe4c16_fk_reports_v" FOREIGN KEY ("variety_id") REFERENCES "reports_variety" ("id") DEFERRABLE INITIALLY DEFERRED;""",
        
        # unit_id
        """ALTER TABLE "reports_dailytaskreport" DROP CONSTRAINT IF EXISTS "reports_dailytaskreport_unit_id_8f71a990_fk_reports_unit_id";""",
        """ALTER TABLE "reports_dailytaskreport" ADD CONSTRAINT "reports_dailytaskreport_unit_id_8f71a990_fk_reports_unit_id" FOREIGN KEY ("unit_id") REFERENCES "reports_unit" ("id") DEFERRABLE INITIALLY DEFERRED;""",
    ]
    
    with connection.cursor() as cursor:
        for query in queries:
            try:
                cursor.execute(query)
                print(f"Executed: {query[:50]}...")
            except Exception as e:
                print(f"Error executing query: {e}")

if __name__ == "__main__":
    fix_db()
